-- Reservations Table Schema (MySQL)
CREATE TABLE IF NOT EXISTS reservations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  confirmation_number VARCHAR(50) NOT NULL UNIQUE,
  guest_id INT NOT NULL,
  room_id INT,
  room_type_id INT NOT NULL,
  rate_plan_id INT NOT NULL,
  check_in_date DATE NOT NULL,
  check_out_date DATE NOT NULL,
  adults INT NOT NULL DEFAULT 1,
  children INT DEFAULT 0,
  total_rate DECIMAL(10, 2) NOT NULL,
  tax_amount DECIMAL(10, 2) DEFAULT 0.00,
  deposit_paid DECIMAL(10, 2) DEFAULT 0.00,
  nights INT GENERATED ALWAYS AS (DATEDIFF(check_out_date, check_in_date)) STORED,
  total_amount DECIMAL(10, 2) GENERATED ALWAYS AS (total_rate + tax_amount) STORED,
  balance_due DECIMAL(10, 2) GENERATED ALWAYS AS (total_rate + tax_amount - deposit_paid) STORED,
  status ENUM('pending', 'confirmed', 'checked_in', 'checked_out', 'cancelled', 'no_show') DEFAULT 'pending',
  special_requests TEXT,
  notes TEXT,
  booked_by_staff_id INT,
  cancelled_by_staff_id INT,
  cancelled_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (guest_id) REFERENCES guests(id) ON DELETE RESTRICT,
  FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE RESTRICT,
  FOREIGN KEY (room_type_id) REFERENCES room_types(id) ON DELETE RESTRICT,
  FOREIGN KEY (rate_plan_id) REFERENCES rate_plans(id) ON DELETE RESTRICT,
  FOREIGN KEY (booked_by_staff_id) REFERENCES staff(id) ON DELETE SET NULL,
  FOREIGN KEY (cancelled_by_staff_id) REFERENCES staff(id) ON DELETE SET NULL,
  INDEX idx_reservations_confirmation (confirmation_number),
  INDEX idx_reservations_guest (guest_id),
  INDEX idx_reservations_room (room_id),
  INDEX idx_reservations_room_type (room_type_id),
  INDEX idx_reservations_dates (check_in_date, check_out_date),
  INDEX idx_reservations_status (status),
  INDEX idx_reservations_check_in (check_in_date, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
